os: osx
language: swift
osx_image: xcode12.2

script:
  - xcodebuild -project 'Deluge Remote.xcodeproj' -scheme 'Deluge Remote' -sdk 'iphonesimulator' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -configuration Debug ONLY_ACTIVE_ARCH=YES build -quiet